version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

ldflags:
  - "-X main.Version={{ .Env.VERSION }}"
  - "-s -w"

goos: linux
goarch: amd64

binary: hello-slsa-{{ .Os }}-{{ .Arch }}
